import type { Metadata } from "next";
import localFont from "next/font/local";
import { Hammersmith_One } from "next/font/google";

import "./globals.css";
import { RootNavigation } from "@/components/RootNavigation";
import Footer from "@/components/Footer";

const helveticaRegular = localFont({
    src: "./fonts/HelveticaNeueRoman.otf",
    variable: "--font-helvetica-regular",
    // weight: "100 900",
});
const helveticaMedium = localFont({
    src: "./fonts/HelveticaNeueMedium.otf",
    variable: "--font-helvetica-medium",
    // weight: "100 900",
});

const hammerSmith = Hammersmith_One({
    variable: "--font-hammersmith-one",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${helveticaRegular.variable} ${helveticaMedium.variable} ${hammerSmith.variable} antialiased font-hregular text-gray-1000 tracking-wide bg-white`}
            >
                <RootNavigation />
                <main className="px-4 md:px-20">{children}</main>

                <Footer />
            </body>
        </html>
    );
}
