import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { RootNavigation } from "@/components/RootNavigation";

const helveticaRegular = localFont({
    src: "./fonts/HelveticaNeueRoman.otf",
    variable: "--font-helvetica-regular",
    // weight: "100 900",
});
const helveticaMedium = localFont({
    src: "./fonts/HelveticaNeueMedium.otf",
    variable: "--font-helvetica-medium",
    // weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${helveticaRegular.variable} ${helveticaMedium.variable} antialiased font-hregular text-gray-1000 tracking-wide bg-white px-4`}
            >
                <RootNavigation />
                {children}
            </body>
        </html>
    );
}
